//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseEleva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracoes
    {
        public int Id { get; set; }
        public int IdiomaId { get; set; }
    
        public virtual Idioma Idioma { get; set; }
    }
}
